package adschool.domain;


public enum RoleNames {
	ROLE_ENSEIGNANT,ROLE_ELEVE,ROLE_PARENT,ROLE_ADMINISTRATEUR,ROLE_AGENT_APPUI,ROLE_DIRECTION,ROLE_SURVEILLANT,ROLE_CENSEUR,ROLE_ECONOME,ROLE_CAISSIER;
}
